app = "collab-editor-ws-rj"
primary_region = "bom"

[build]
  dockerfile = "Dockerfile"

[env]
  WS_PORT = "8080"
  WS_HOST = "0.0.0.0"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"